batch_size: 256
dropout: 0.0
encoder: GAT
epochs: 500
hidden_dim_encoder: 256
hidden_dim_projector: 1024
input_dim_projector: 1024
k: 3
learning_rate: 0.0003
margin: 0.4
momentum: 0.001
n_layers_conv: 3
node_embedding_dim: 10
node_masking: 0.5
num_edge_features: 5
num_node_features: 7
num_samples: 1000000
output_dim_projector: 64
precision: 32
pooling: add
radius: 1.5
residual_connection: dense
seed: 42
temperature: 0.07
warmup_epochs: 10
weight_decay: 1.0e-06
