[build-system]
requires = ["hatchling<=1.18.0"]
build-backend = "hatchling.build"

[project]
name = "PharmacoMatch"
version = "2025.6.11"
dependencies = [
    "torch==2.7.0",
    "torch_geometric==2.6.1",
    "lightning==2.5.1",
    "torchmetrics==1.7.2",
    "tensorboard==2.19.0",
    "matplotlib==3.10.3",
    "scikit-learn==1.7.0",
    "pandas==2.3.0",
    "umap-learn==0.5.7",
    "datashader==0.18.1",
    "bokeh==3.7.3",
    "holoviews==1.20.2",
    "cdpkit==1.2.2",
    "rdkit==2025.3.2",
    "jupyter==1.1.1",
    "ipykernel==6.29.5",
]
requires-python = ">=3.10"
readme = "README.md"