batch_size: 4096
epochs: 5000

n_layers_conv: 3
output_dims_conv: 128
output_dims_lin: 1024
dropout: 0.3
temperature: 0.5

learning_rate: 0.05
opt_eta: 0.001
opt_weight_decay: 1.0e-06
warmup_epochs: 10

num_samples: 100000
num_edge_features: 5
num_node_features: 7

seed: 42