batch_size: 256
dropout: 0.2
dropout_projector: 0.2
encoder: NNConv
epochs: 500
freeze_encoder: false
hidden_dim_encoder: 64
hidden_dim_projector: 1024
input_dim_projector: 1024
k: 3
learning_rate: 0.001
margin: 10.
momentum: 0.001
n_layers_conv: 3
n_layers_projector: 3
node_embedding_dim: 10
node_masking: 0.5
num_edge_features: 5
num_node_features: 7
num_samples: 100000
output_dim_projector: 256
pooling: add
positives_multiplier: 1
precision: 32
radius: 0.25
radius_negative: 1.5
regularization_lambda: 0
regularization_p_norm: 1
residual_connection: dense
seed: 42
temperature: 0.07
warmup_epochs: 10
weight_decay: 1.0e-06
