batch_size: 256
dropout: 0.2
dropout_projector: 0.2
encoder: NNConv
epochs: 500
hidden_dim_encoder: 64
hidden_dim_projector: 1024
input_dim_projector: 1024
learning_rate: 0.001
margin: 0.1
n_layers_conv: 3
n_layers_projector: 3
node_embedding_dim: 10
num_edge_features: 5
num_node_features: 7
num_samples: 100000
output_dim_projector: 512
pooling: add
positives_multiplier: 1
precision: 32
radius: 0.25
radius_negative: 1.5
residual_connection: dense
seed: 42
